// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWOFZJ5fXqtYmhjEHt31xC4OyiqMzeUhg',
    appId: '1:130615476237:web:babd060e5ccb4ea925d544',
    messagingSenderId: '130615476237',
    projectId: 'cave-vin-jo',
    authDomain: 'cave-vin-jo.firebaseapp.com',
    storageBucket: 'cave-vin-jo.firebasestorage.app',
    measurementId: 'G-VCXSZ9WZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Ur9IQbyQ8YeOWLZfQQDIINtvQZfbDV8',
    appId: '1:130615476237:android:19d712ac3166188625d544',
    messagingSenderId: '130615476237',
    projectId: 'cave-vin-jo',
    storageBucket: 'cave-vin-jo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tNIi8Q7hyG0gpHjC78bKIDEZDBXqEUo',
    appId: '1:130615476237:ios:ab4cb0a8fbcf75bd25d544',
    messagingSenderId: '130615476237',
    projectId: 'cave-vin-jo',
    storageBucket: 'cave-vin-jo.firebasestorage.app',
    iosBundleId: 'com.example.caveVinJo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWOFZJ5fXqtYmhjEHt31xC4OyiqMzeUhg',
    appId: '1:130615476237:web:f596352171fde86325d544',
    messagingSenderId: '130615476237',
    projectId: 'cave-vin-jo',
    authDomain: 'cave-vin-jo.firebaseapp.com',
    storageBucket: 'cave-vin-jo.firebasestorage.app',
    measurementId: 'G-QFXP0VEX0E',
  );
}
